# Use the official SQL Server image
FROM mcr.microsoft.com/mssql/server:2022-latest

# Set environment variables for SQL Server
ENV MSSQL_SA_PASSWORD=YourStrong@Passw0rd \
    MSSQL_PID='Developer' \
    ACCEPT_EULA=Y
